#!/usr/bin/env ruby

require_relative './time-fetcher'

tt = TrackingTime.new(
    months_ago: ARGV[0] || '0'
)

tt.entries.each do | ent |
    puts ent.to_s
end

puts "#{tt.hours} logged #{tt.duration} (expected: #{tt.expected_hours})"
